baseURL = 'http://hizv.me'
title = "Himi's Notes"
theme = 'refined'

languageCode = 'en-us'

[Author]
  name = "Himanish"
  bio = "These infernal revelations beamed through the cryptic shadows are totally uncool."

[Social]
  github = "hizv"
  twitter = "qqqzv"

[Permalinks]
  posts = "/:filename/"
  notes = "/notes/:filename/"

[Taxonomies] 
  category = "categories" # SINGULAR = "PLURAL"
  tag = "tags"
  series = "series"


[Params]
  mainSections = ["posts", "notes"]

  [Params.source]
    url = "https://github.com/hizv/p-site"
    org_dir = "content-org"
    md_dir = "content"
    ox_hugo = true
  [[Params.social]]
    name = "Github"
    link = "https://github.com/hizv/"
    relme = true
  [[Params.social]]
    name = "Twitter"
    link = "https://twitter.com/qqqzv/"
