#+TITLE: Linguistics
#+date: 2022-05-15
#+author: Himanish

#+hugo_section: notes
#+hugo_categories: hum
#+hugo_menu: :menu "main" :weight 2001

#+startup: content

#+hugo_base_dir: ../
#+hugo_section: ./

#+hugo_weight: auto
#+hugo_auto_set_lastmod: t

* What is Language?
- To some people of Africa, a newborn child is a /kintu/, a ‘thing’, not yet a /muntu/, a ‘person’. Only by the act of learning language does the child become a human being. It distinguishes us from other animals.
** Linguistic Knowledge
*What does it mean to know a language?*
*** Sound system
Knowing the sounds (or signs for the deaf)
- To pronounce French words, we need to use non-English sounds
- The /nk/ sound may begin a word in Ghana but not in English
*** Words
- Which sequences of sounds are related to specific meanings.
- *Arbitary relation of form and meaning*: There is no natural or intrinsic relationship between the way a word is pronounced (or signed) and its meaning.
- *Sound symbolism*: The notion that certain sound combinations occur in semantically similar words, e.g. gl in gleam, glisten, glitter, which all relate to vision. However, such words are a very small part of any language,
*** Creativity
- Combine sounds to words, words to phrases, phrases to sentences
- Not only making new sentences but also in understanding new/novel ones.
- Knowing what sentences are appropriate in various situations
*** Well-formed Sentences
 Linguistic knowledge includes rules for forming sentences, which must be finite in length and finite in number so they can be stored in our finite brains
** Grammar
Grammar includes
- Phonology: rules for combining sounds into words
- Morphology: rules of word formation
- Syntax: rules for combining words to phrases and phrases to sentences
- Semantics: rules for assigning meaning

*** Descriptive Grammar
- Linguist's model of mental grammar shared by the speakers
- Won't tell you how to speak, only basic linguistic knowledge
- Every language's grammar is equally complex, logical and capable. No dialect is superior.
*** Prescriptive Grammar
- Language ‘purists’: some language versions are better than others, certain ‘correct’ forms all educated people should use, language change is corruption.
- Greek Alexandrians in the first century, Arabic scholars at Basra in the eighth century, numerous English grammarians of the 18th and 19th centuries
- Renaissance: middle class wanted their children to speak 'upper' class dialect, leading to many prescriptive grammars
- Before Lowth's /A Short Introduction to English Grammar with Critical Notes/ in 1762, practically everyone – upper class, middle class and lower class – said ‘I don’t have none’, ‘You was wrong about that’ and ‘Matilda is fatter than me’.
  - Lowth, however, decided that ‘two negatives make a positive’ and therefore one should say ‘I don’t have any’, that even when you is singular it should be followed by the plural were and that I not me, he not him, they not them and so forth should follow than in comparative constructions.
  - However, Romance languages use double negatives e.g. French, Italian
  - Many of these prescriptive rules were based on Latin grammar
  - Because Lowth was influential and because the rising new class wanted to speak ‘properly’, many of these new rules were legislated into English grammar, at least for the prestige dialect (dialect usually spoken by people in positions of power)
- In a society where ‘linguistic profiling’ is used to discriminate against speakers of a minority dialect, it may behove those speakers to learn the prestige dialect rather than wait for social change.
  - But linguistically, prestige and standard dialects do not have superior grammars.
- Writing is not acquired naturally through simple exposure to others speaking the language, but must be taught, so writing will follow certain prescriptive rules that spoken language does not, with little dialectical variation.
*** Teaching Grammars
- A set of language rules written to help speakers learn a foreign language or a different dialect of their own language.
- Teaching grammars assume the student already knows one language and compares the grammar of the target language with the grammar of their native language
- Meaning of word given by a gloss (parallel native word) e.g. 'house' is English gloss for French /maison/
- New sounds are described by reference to known sounds e.g. French sound u in the word tu by instructions such as ‘Round your lips while producing the vowel sound in tea’.
- Difficult for adults to learn a second language without formal instruction, even after living in that country
*** Universal Grammar
- Rules representing the universal properties of all languages constitute a Universal Grammar (UG).
- UG is the blueprint that all languages follow that forms part of the child’s innate capacity for language learning
- The comparative study of many different languages is of central importance to this enterprise.
*** Sign Languages
- Slips of the hand occur similar to slips of the tongue
- Finger fumblers amuse signers just as tongue twisters amuse speakers
- Deaf children babble with their hands, just as hearing children babble with their vocal tracts
** Human vs Animal "Language"
- Discreteness: larger linguistic units are perceived to be composed of smaller linguistic units
- Displacement: the capacity to talk (or sign) messages that are unrelated to here and now
* Brain and Language
* Morphology
