#+title: Quantum Computing
#+date: 2022-05-26
#+author: Himanish

#+hugo_section: notes
#+hugo_categories: hum
#+hugo_menu: :menu "main" :weight 2001

#+startup: content

#+hugo_base_dir: ../
#+hugo_section: ./

#+hugo_weight: auto
#+hugo_auto_set_lastmod: t
#+hugo_custom_front_matter: :mathjax t
#+hugo_paired_shortcodes: %sidenote


* Qubits
*** Computational Basis States
\(\ket{0} := \begin{bmatrix}
1 \\
0
\end{bmatrix}
\)
\(\ket{1} := \begin{bmatrix}
0 \\
1
\end{bmatrix}
\)
*** Quantum State
The quantum state of a qubit is a vector of unit length in a two-dimensional complex vector space known as state space.
- Normalisation Constraint: \(|\alpha|^2+|\beta|^2 = 1\) for \(\alpha \ket{0} + \beta\ket{1}\)
* Quantum Logic Gates
** NOT Gate
\[ X(\alpha\ket{0}+ \beta\ket{1})=\alpha\ket{1}+\beta\ket{0}\]
- Function application is just matrix multiplication.
\[X = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}\]
- Notation originated from Pauli's \(\sigma_x\) operation to describe rotations around x-axis
- \(XX = I\)
** Quantum wire
- If input \(\ket{\psi}\) then output is also \(\ket{\psi}\)
- Hard to implement; quantum states are fragile.
- If state is stored in a neutrino then state will be well preserved; can easily pass through a mile of lead without disturbance
  - But quantum gates can't be implemented with them as they won't interact
** Hadamard Gate
 \[H\ket{0}= \frac{\ket{0}+\ket{1}}{\sqrt{2}}\]
 \[H\ket{1}= \frac{\ket{0}-\ket{1}}{\sqrt{2}}\]

 \[H(\ket{0}+ \beta\ket{1})= \frac{\alpha-\beta}{\sqrt{2}}\ket{0}+\frac{\alpha-\beta}{\sqrt{2}}\ket{1}\]

\[H = \frac{1}{\sqrt{2}} \begin{bmatrix} 1 & 1 \\ 1 & -1 \end{bmatrix}\]
- \(HH = I\)
- Many algorithms first use Hadamard gates to “spread out” in quantum states, i.e., in superpositions of multiple computational basis states, which makes it possible to take computational shortcuts.  At the end of the algorithm they use clever patterns of cancellation and reinforcement to bring things back together again into one (or possibly a few, in the many-qubit case) computational basis state, containing the desired answer
** Measurement
- If you measure a qubit is in the state \(\alpha\ket{0}+\beta\ket{1}\) in the computational basis it gives you a classical bit of information: either 0 with probability \(|\alpha|^2\), or 1 with probability \(|\beta|^2\)
- A fundamental fact about this measurement process is that it disturbs the state of the quantum system.  After the measurement, if you get the outcome 0 then the state of the qubit afterwards (the “posterior state”) is the computational basis state \(\ket{0}\) and vice-versa.
  - No matter what the outcome, \(\alpha\) and \(\beta\) are gone. And so you can’t get any more information about them.
** General single-qubit gates
- A matrix  \(U\) is unitary if \(U^{\dag}U = I\) where \(U^{\dag}\) is the adjoint of  \(U\): \[U^{\dag} := (U^T)^*\]
#+begin_sidenote
\(\dag\) is called the dagger operation, or Hermitian conjugation, or just the conjugation operation.
#+end_sidenote
